### ISSUE TITLE
`requirements.txt` should include `psutil`

### ISSUE THREAD

**Issue by m-ueberall** [starnightcyber/findSubDomains#5]
Without `psutil`, a call to `findSubDomains.py` will result in
```
pkg_resources.DistributionNotFound: The 'psutil>=5.7.0; sys_platform != "win32" or platform_python_implementation == "CPython" and extra == "recommended"' distribution was not found and is required by the application
```
(tested w/ Python 3.8.0, pyenv 1.2.1 on Ubuntu Bionic)

**Comment by starnightcyber** [comment]
OK, thank you @m-ueberall .
Add dependency psutil==5.7.0 in requirement.txt.
https://github.com/starnightcyber/findSubDomains/blob/ae57fa2c42dc55471932e4303601c09c97e47dad/requirements.txt#L11
